### PR TITLE
Update CloudWatch Metrics for AWS IoT SiteWise

### PR DESCRIPTION
**Pull request by Deepali1211**
Update CloudWatch Metrics for AWS IoT SiteWise.

Issue ref# https://github.com/grafana/grafana/issues/92747

### CODE REVIEW

**Comment by iwysiu** [comment]
Hi @Deepali1211 , thanks for the pr! Based on the [AWS docs](https://docs.aws.amazon.com/iot-sitewise/latest/userguide/monitor-cloudwatch-metrics.html), it looks like the the old `Gateway` metrics were also valid, so I think we should put those back and have both the `Gateway` and the `IoTSiteWisePublisher` metrics. Also could you add the other metrics from the docs so that we have all of them?

**Comment by Deepali1211** [comment]
I have added all the Version 1 and Version 2 metrics.

**Review by iwysiu — COMMENTED** [review]
Hi @Deepali1211 , thanks for adding all the metrics!
We're almost there, 2 more changes and I can merge it
1) If you run `mage test` in the file, it'll alphabetize the `AWS/IotSiteWise` metrics for you and can copy that into the file.
2) Can you replace the `AWS/IotSiteWise` line on 3295 (in the Dimensions Map) with 

```
"AWS/IoTSiteWise":                    {"AccountId", "GatewayId", "PropertyGroup", "Reason", "SourceName", "StreamName", "ThrottledAt"},
```

**Comment by Deepali1211** [comment]
Done.
Also, there are entries like "OpcUaCollector.Heartbeat" and "OPCUACollector.Heartbeat". 
Considering keys to be case insensitive, I have kept single entry.
Do you want me to keep metrics with both keys `OpcUaCollector` and `OPCUACollector`?

**Comment by iwysiu** [comment]
> Done. Also, there are entries like "OpcUaCollector.Heartbeat" and "OPCUACollector.Heartbeat". Considering keys to be case insensitive, I have kept single entry. Do you want me to keep metrics with both keys `OpcUaCollector` and `OPCUACollector`?

Thanks! I think we've found in the past that metrics are case sensitive, so can you keep both keys?

**Comment by Deepali1211** [comment]
Added two metrics with `OPCUACollector` as per their docs.
They only have two metrics with OPCUACollector and have duplicate entries with OpcUaCollector.
image

**Review by iwysiu — APPROVED** [review]
Thanks @Deepali1211 ! I'll get this merged and into the Cloudwatch plugin

**Pull request merged**
