### PR TITLE
Upgrade grafana-plugin-sdk-go to the latest version

### PR DESCRIPTION
**Pull request by idastambuk**

### CODE REVIEW

**Comment by sarahzinger** [comment]
This build seems to be hanging for mysterious reasons??

Screenshot 2023-08-09 at 4 44 39 PM

**Review by sarahzinger — CHANGES_REQUESTED** [review]
This build seems to be hanging for mysterious reasons??

Screenshot 2023-08-09 at 4 44 39 PM

Also looks like we're committing some file called .DS_Store which seems unintentional?

**Comment by kevinwcyu** [comment]
you can run `mage drone` to update the signature. that should unblock the build. you'll need the drone cli setup with `DRONE_SERVER` and `DRONE_TOKEN` which you can find in when you login to your drone account page

**Comment by idastambuk** [comment]
> you can run `mage drone` to update the signature. that should unblock the build. you'll need the drone cli setup with `DRONE_SERVER` and `DRONE_TOKEN` which you can find in when you login to your drone account page

That worked, thanks so much!

**Review by sarahzinger — APPROVED** [review]
Coolio! Just checking were you able to test this manually with grafana and/or another datasource! Let me know if you want help doing so. Thanks for looking into this!

**Comment by idastambuk** [comment]
> Coolio! Just checking were you able to test this manually with grafana and/or another datasource! Let me know if you want help doing so. Thanks for looking into this!

Tested with Cloudwatch and Athena and looks good!

**Comment by idastambuk** [comment]
Just need someone from @grafana/grafana-operator-experience-squad to review this as well 🙏🏻🙏🏻🙏🏻

**Review by leandro-deveikis — APPROVED** [review]
LGTM!

**Pull request merged**
