### PR TITLE
Fix ec2 with endpoint connection

### PR DESCRIPTION
**Pull request by iwysiu**
Fixes grafana/support-escalations#1531

### CODE REVIEW

**Review by andresmgot — APPROVED** [review]
LGTM!

**Review by sunker — APPROVED** [review]
Yes looks good! Would be great if we could test this in ec2 (a workspace in aws would be even better) using cloudwatch before releasing a new version of the sdk. 

Steps to reproduce in the escalation, and you should be able to use endpoint `monitoring.us-east-2.amazonaws.com` while testing.

**Comment by sunker** [comment]
Nice @iwysiu! We also need to bump the sdk version in all plugins that use it.

**Comment by andresmgot** [comment]
we may want to work on https://github.com/grafana/grafana-aws-sdk/issues/46 before updating all the plugins

**Comment by sunker** [comment]
Yeah makes sense

**Pull request merged**
